### ISSUE TITLE
Request: Reload textures on Focus

### ISSUE THREAD

**Issue by DMJC** [eh2k/teapot-viewer#2]
Hi,

Can you please add a feature where textures reload when the application is selected? E.g if a user has two screens they load a model into the viewer, then they switch to a 2d editor like photoshop, edit their textures, and then click back on the viewer window. When the viewer window becomes active it then reloads the textures updating the model with whatever the user was editing in the 2d editor. This can make texturing a much simpler process. Even better would be if you can select which textures to display on the model.

**Comment by eh2k** [comment]
In the current Version v1.0a 
 # Textures are now releaded automatically...
